---
abstract: 'Perl module to test for correct RG numbers'
author:
  - 'Renato CRON <rentocron@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-BR-RG
requires:
  Exporter: 0
  perl: 5.004
resources:
  bugtracker: http://github.com/renatocron/Business--BR--RG/issues
  repository: http://renatocron@github.com/renatocron/Business--BR--RG.git
version: 0.001
